import type { FreelancerData } from "./types";

export const defaultData = (): FreelancerData => ({
  profile: {
    name: "",
    title: "Freelancer",
    skills: [],
    hourlyRate: 75,
    currency: "EUR",
    experienceYears: 3,
    bio: "",
    portfolio: [],
    availability: "available",
  },
  jobs: [
    {
      id: "job-001",
      title: "Next.js dashboard voor SaaS startup",
      client: "TechFlow BV",
      description:
        "We zoeken een ervaren frontend developer voor een analytics dashboard. React/Next.js, TypeScript, Tailwind. Duur: 4-6 weken.",
      budget: "€4.000 - €6.000",
      skills: ["Next.js", "React", "TypeScript", "Tailwind CSS"],
      platform: "LinkedIn",
      postedAt: "2026-09-10",
      status: "open",
    },
    {
      id: "job-002",
      title: "AI chatbot integratie in bestaande webapp",
      client: "RetailPlus",
      description:
        "Integratie van een AI-assistent (OpenAI/Claude) in onze e-commerce platform. API design, streaming responses, rate limiting.",
      budget: "€80/uur",
      skills: ["AI", "Node.js", "API", "Python"],
      platform: "Upwork",
      postedAt: "2026-09-12",
      status: "open",
    },
    {
      id: "job-003",
      title: "Video editing automation pipeline",
      client: "ContentCreator Co",
      description:
        "Automatiseer short-form video productie: script → TTS → visuals → export. Remotion of FFmpeg. Python preferred.",
      budget: "€3.500 fixed",
      skills: ["Python", "FFmpeg", "Remotion", "Automation"],
      platform: "Direct",
      postedAt: "2026-09-14",
      status: "open",
    },
    {
      id: "job-004",
      title: "WordPress naar headless CMS migratie",
      client: "MediaGroep NL",
      description:
        "Migratie van 200+ artikelen naar Sanity CMS met Next.js frontend. SEO behoud, redirect mapping.",
      budget: "€5.000 - €8.000",
      skills: ["Next.js", "Sanity", "WordPress", "SEO"],
      platform: "Freelance.nl",
      postedAt: "2026-09-08",
      status: "open",
    },
    {
      id: "job-005",
      title: "Mobile app MVP (React Native)",
      client: "FitStart",
      description:
        "MVP fitness tracking app: onboarding, workout logging, basic analytics. iOS + Android. 8 weken timeline.",
      budget: "€10.000 fixed",
      skills: ["React Native", "TypeScript", "Firebase"],
      platform: "Upwork",
      postedAt: "2026-09-13",
      status: "open",
    },
    {
      id: "job-006",
      title: "YouTube Shorts editor (3x per week)",
      client: "GrowthLab Media",
      description:
        "Long-form podcast → 3 Shorts per week. Jump cuts, captions, B-roll, branded intro/outro. Premiere Pro of DaVinci.",
      budget: "€400/maand retainer",
      skills: ["Premiere Pro", "DaVinci Resolve", "YouTube Shorts", "Captions"],
      platform: "Upwork",
      postedAt: "2026-09-14",
      status: "open",
    },
    {
      id: "job-007",
      title: "Remotion developer voor faceless video SaaS",
      client: "AutoClip Inc",
      description:
        "Bouw een Remotion template systeem: dynamische scenes, TTS sync, batch export. TypeScript + React. Bestaande Python pipeline.",
      budget: "€120/uur",
      skills: ["Remotion", "React", "TypeScript", "FFmpeg", "Automation"],
      platform: "RemoteOK",
      postedAt: "2026-09-12",
      status: "open",
    },
    {
      id: "job-008",
      title: "TikTok/Reels editor voor fitness creator",
      client: "Coach Mike",
      description:
        "15-30 sec hooks, trending audio sync, on-screen text, 5 reels/week. Snelle turnaround (48u). CapCut of Premiere.",
      budget: "€50/video",
      skills: ["CapCut", "Premiere Pro", "TikTok", "Motion Graphics"],
      platform: "Direct",
      postedAt: "2026-09-15",
      status: "open",
    },
    {
      id: "job-009",
      title: "Color grading + sound design documentaire",
      client: "Northlight Films",
      description:
        "15-min indie documentaire. DaVinci Resolve grading, basic sound design, export DCP-ready master.",
      budget: "€2.800 fixed",
      skills: ["DaVinci Resolve", "Color Grading", "Sound Design"],
      platform: "Freelance.nl",
      postedAt: "2026-09-11",
      status: "open",
    },
  ],
  proposals: [],
  projects: [],
  invoices: [],
});
